### ISSUE TITLE
How to use this API in React?

### ISSUE THREAD

**Issue by Launchpad5682** [dicebear/dicebear#154]
How can I use the response svg in React as the response returned is in HTML and React needs JSX. I tried few tricks but didn't able to use it.

**Comment by FlorianKoerner** [comment]
The safest way is to use it with "dataURI" option.

```tsx
const avatar = createAvatar(style, {
  dataUri: true,
})

<img src={avatar} />
```

CodeSandbox example:
https://codesandbox.io/s/pensive-herschel-8ybqw?file=/src/App.js

But also `dangerouslySetInnerHTML` should not cause any problems, because at least the official avatar styles _should_ not output dangerous code. But I wouldn't use `dangerouslySetInnerHTML` either.
