### ISSUE TITLE
Way to return png or jpg?

### ISSUE THREAD

**Issue by Lioncat2002** [dicebear/dicebear#173]
Hello I had been trying out this api
but I noticed that it returns an svg
is there a way to return png file?

I also noticed that the HTTP-API examples which return pngs in 
https://www.npmjs.com/package/@dicebear/avatars/v/2.0.0-beta.3
Don't work anymore

**Comment by FlorianKoerner** [comment]
With version 2.0 we switched to SVG format, which is supported by all major browsers. Due to the fact that they are only text files, the creation of avatars is particularly fast.

However, depending on the use case, the SVG format may not work. It is planned that the API will support JPEG and PNG formats from around the end of November. 

See also:
#171

**Comment by FlorianKoerner** [comment]
Posted a small update on this in the discussion.
https://github.com/dicebear/dicebear/discussions/171#discussioncomment-1615966

**Comment by FlorianKoerner** [comment]
It is now officially supported. #179
