### ISSUE TITLE
Open Peeps - Hair/Facial Hair Color Issue

### ISSUE THREAD

**Issue by NickCascella** [dicebear/dicebear#175]
Hi, I've tried to set  different colors on various hairstyles but only a few actually changed colors. Here is a list of hairstyles I could not get any color for. Additionally, facial hair options do not seem to change color with the exceptions of Full 4 and Mustache 9. Wanted to know if this is intentional or not, thanks.

**Non color responsive hair styles**

- afro
- bangs2
- bantuknots
- bun
- bun2
- buns
- dreads2
- flatTop
- flatTopLong
- hairBeanie
- long
- longAfro
- longBangs
- longCurly
- medium 1-3
- medium 1 & 3
- mediumStraight
- noHair2
- pomp
- shaved 1-3
- short 1-3, 5

**Comment by FlorianKoerner** [comment]
That is intentional. Actually, the Open Peeps avatars were monochrome. Colors were then added for parts that had an outline.

- https://www.openpeeps.com/

I think DiceBear is also the only library that lets you customize the hair color for OpenPeeps. I can't find such an option elsewhere:

- https://blush.design/collections/open-peeps/open-peeps/character-avatar/j6AG04iExidnuSgc?c=Skin_0%7Eedb98a
- https://www.opeeps.fun/

I understand that this can be irritating, as discussed here before:
https://github.com/dicebear/dicebear/issues/168

I think here it could be a solution to make two options out of "hairColor". One option for the original black and one for the original white areas. Currently only the original white areas can be colored.

**Comment by FlorianKoerner** [comment]
Option renamed to `headContrastColor` with Version 5.0 to clarify that it is not directly related to the hair color.
