### ISSUE TITLE
Add gender switch to avataaars

### ISSUE THREAD

**Issue by smeijer** [dicebear/dicebear#21]
Would be nice to have a `gender` (`male|female`) option for the `avataaars`. I tried to fake it by setting the hair length. But then I get "females" with mustaches. 

I know, nothing wrong with that... But also not suited for all my users.

**Comment by FlorianKoerner** [comment]
I had once decided against such an option. Because as you have already mentioned: What is female and what is male?

However, you can define the options so that either a very female or a very male character comes out. The configurator on avatars.dicebear.com might also help.

For example, there is also an option on how likely it is that the character has a mustache.


Examples:

Female: https://avatars.dicebear.com/v2/avataaars/example.svg?options[top][]=longHair&options[top][]=hat&options[topChance]=100&options[accessoriesChance]=40&options[facialHairChance]=0

Male: https://avatars.dicebear.com/v2/avataaars/example.svg?options[top][]=eyepatch&options[top][]=hat&options[top][]=shortHair&options[topChance]=79&options[hatColor][]=pastel&options[hatColor][]=heather&options[hatColor][]=gray&options[hatColor][]=blue&options[hatColor][]=black&options[hatColor][]=white&options[hairColor][]=gray&options[hairColor][]=platinum&options[hairColor][]=pastel&options[hairColor][]=blonde&options[hairColor][]=black&options[hairColor][]=auburn&options[hairColor][]=brown&options[accessoriesChance]=13&options[facialHairChance]=78&options[facialHairColor][]=auburn&options[facialHairColor][]=black&options[facialHairColor][]=brown&options[facialHairColor][]=pastel&options[facialHairColor][]=platinum&options[facialHairColor][]=gray&options[facialHairColor][]=blonde&options[clothesColor][]=black&options[clothesColor][]=blue&options[clothesColor][]=gray&options[clothesColor][]=pastel&options[clothesColor][]=heather&options[clothesColor][]=white&options[eyes][]=happy&options[eyes][]=roll&options[eyes][]=dizzy&options[eyes][]=defaultValue&options[eyes][]=cry&options[eyes][]=close&options[eyes][]=side&options[eyes][]=squint&options[eyes][]=surprised&options[eyes][]=wink&options[eyes][]=winkWacky

**Comment by smeijer** [comment]
fair enough.

**Comment by AmineAssali** [comment]
Hello @FlorianKoerner i remember that i have tested the http request you have posted about a year ago and it worked, but now it doesn't work, do you have any idea why ?? 

Thanks in advance.

**Comment by FlorianKoerner** [comment]
Looks like a bug in the api. I will have a look at it.

The examples earlier in this issue use a deprecated variant of how to pass options. Try the following two URLs. They should work.

Female: https://avatars.dicebear.com/v2/avataaars/example.svg?top[]=longHair&top[]=hat&topChance=100&accessoriesChance=40&facialHairChance=0

Male: https://avatars.dicebear.com/v2/avataaars/example.svg?mode=exclude&top[]=longHair&topChance=80&hatColor[]=pastel&hatColor[]=pink&hatColor[]=red&hairColor[]=red&hairColor[]=pastel&accessoriesChance=10&facialHairChance=80&facialHairColor[]=red&facialHairColor[]=pastel&clothesColor[]=red&clothesColor[]=pink&eyes[]=hearts

**Comment by AmineAssali** [comment]
@FlorianKoerner Thank you for you response,  but for the male URL i still getting a face with long hair and a moustach

**Comment by FlorianKoerner** [comment]
@AmineAssali you are right. The following links should work.

**Long Hair & without facialHair**
https://api.dicebear.com/4.x/avataaars/svg?facialHairProbability=0&seed=Opal&top[]=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02

**Short Hair**
https://api.dicebear.com/4.x/avataaars/svg?top[]=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban

**Comment by bitcloudTheFirst** [comment]
This is definitely a bug. Having avatars that don't generate reliable genders makes a great system useless.

**Comment by AhmedOThman1** [comment]
When I try to use the avataaars new link 
https://api.dicebear.com/7.x/avataaars/png

I face this problem that I can't us **top[]** cause its throw an error 
`{"statusCode":400,"code":"FST_ERR_VALIDATION","error":"Bad Request","message":"querystring/top/0 must be string"}`

How can I use this to generate a male avatar?

my test link below
https://api.dicebear.com/7.x/avataaars/png?seed=mohamed&mouth=smile&eyes=default,happy&eyebrow=default&topChance=90&accessoriesChance=10&facialHairChance=80&top[]=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban
