### ISSUE TITLE
How could I `createAvatar` asynchronously  ?

### ISSUE THREAD

**Issue by BlackCod3** [dicebear/dicebear#225]
I use dicebear/adventurer in my React Native (0.68.2) app. 
I have to display multiple avatars (up to 100) on a screen. I'm facing serious performance issue. The loading time seems to be very correlated to the number of avatar i'm displaying. This makes me think that the issue comes from the synchronous function `createAvatar`. So is there a way to generate an avatar asynchronously ? Locally, not via the web api

Many thanks

**Comment by FlorianKoerner** [comment]
Hi @BlackCod3 

DiceBear is very fast! You can check the performance of the current version here:
https://jsbench.me/5hkvh1shq1/1

See also: https://github.com/dicebear/dicebear/discussions/172

The problem with React Native is the rendering of the SVGs. There are countless posts on the web about this. It has been discussed here as well:

- https://github.com/dicebear/dicebear/discussions/199
- https://github.com/dicebear/dicebear/issues/87

From our side we can't do anything about it, because we only provide the SVG strings and don't do the rendering.

**Comment by BlackCod3** [comment]
Thanks for your quick response @FlorianKoerner 
And shout-out to you guys maintaining such an awesome lib
