### ISSUE TITLE
Generate Seed based on Props

### ISSUE THREAD

**Issue by Arinji2** [dicebear/dicebear#273]
Maybe add a way to generate a svg seed based on the props you set like for example you have an svg where you have inputted the hair to be white and the body to be small etc.. so you can generate a seed with those properties

**Comment by FlorianKoerner** [comment]
Hi @Arinji2 

I am not sure if I have understood your suggestion correctly.

Most of the properties can already be controlled with the options.

![image](https://user-images.githubusercontent.com/647303/217380184-6df3b98a-e2b8-49dd-bb6e-34025674f7e6.png)

The seed is only used as a value for the PRNG to reliably generate identical random values for an avatar. The seed is not meant to pass the options.

**Comment by Arinji2** [comment]
Yea but like imagine in a situation where i have all of the options set by myself.. if i want to recreate that same avatar im gonna have to save all the prooerties and then use them to make it again. Instead maybe a way to create a seed based on the all the properties set by the user

**Comment by FlorianKoerner** [comment]
I'm sorry, but the seed is not so easy to calculate. If it is possible at all.

**Comment by pierroo** [comment]
Did you find a solution to that @Arinji2 ?

I am facing the same requirements, where instead of storing all the assets names / categories in my user info,
I just wanna have that one seed that CreateAvatar will take as a prop to regenerate the exact same output.

there must be a way; as of now if for example I wanna generate a randomized avatar from the seed I use:
`const randomNumber = Math.random().toString();`
then I feed it to CreateAvatar and it always generate me a new variation.

But on the other way around, if I want to get the generated seed from a manual selection of assets I made, I just don't know how.

**Comment by Arinji2** [comment]
Hiya, sorry it's been a while since I worked on the project needing dicebear, basically I just stored all the props of the Avatar in my db, it works better than storing a png. So like rotation, seed, hat etc. You can get from the db and then insert it into the create avatar

**Comment by pierroo** [comment]
Well you mention inserting seed from db, that's exactly what I'm looking for: how do we get a seed based on all picked elements? :)

**Comment by FlorianKoerner** [comment]
I don't understand the benefit. Maybe you can pick me up there mentally. Why not create a random seed and save it to create the same avatar again later based on this seed? A same seed always creates the same avatar. Or if you use options: Why not save exactly these options?

**Comment by FlorianKoerner** [comment]
You really just have to set the same options and you get the same avatar - over and over again. If you don't set a seed, the seed is an empty string.

https://github.com/dicebear/dicebear/blob/7.x/packages/%40dicebear/core/src/utils/prng.ts#L25

There is actually no reason (for me) to calculate the seed, because you set it when you first created the avatar, so you should know it.

If you have observed something different, please give an example code. Maybe there is an error then.

I'm just not sure if there is a mistake or misunderstanding.

**Comment by Arinji2** [comment]
> Well you mention inserting seed from db, that's exactly what I'm looking for: how do we get a seed based on all picked elements? :) 



Well what you could do is making something of your own, basically the first part is the seed, then add the rest of the props has integers. You can't use the seed only since it's just the base.

**Comment by FlorianKoerner** [comment]
That's right. But why not save the options to generate the same avatar again? 🙂

**Comment by pierroo** [comment]
> I don't understand the benefit. Maybe you can pick me up there mentally. Why not create a random seed and save it to create the same avatar again later based on this seed? A same seed always creates the same avatar. Or if you use options: Why not save exactly these options?

Obviously I could save the options as a json and refill the createAvatar.
Json would be like {
Hat: variant_name,
Shoes: variant_name,
Clothes: variant_name,
Etc
}

Yes i initially use an empty string as seed first time the user enter the avatar editor, and obviously it gives the same default avatar for all.
But then the user browses assets categories (hats / shoes / clothes etc) and pick one asset in each.

Ideally, I would like to know the new corresponding seed that matches this unique combination of assets picked.

It's just easier to save in the Db. Easier to re-feed the createAvatar through this unique string instead of a json

**Comment by Arinji2** [comment]
> > Well you mention inserting seed from db, that's exactly what I'm looking for: how do we get a seed based on all picked elements? :)
> 
> Well what you could do is making something of your own, basically the first part is the seed, then add the rest of the props has integers. You can't use the seed only since it's just the base.


try out this @pierroo

**Comment by pierroo** [comment]
> > Well you mention inserting seed from db, that's exactly what I'm looking for: how do we get a seed based on all picked elements? :)
> 
> Well what you could do is making something of your own, basically the first part is the seed, then add the rest of the props has integers. You can't use the seed only since it's just the base.

actually, you can use the seed alone to generate an avatar.
it's even part of their documentation to have it the single parameter passed to CreateAvatar and it works perfectly.

But I'm starting to believe it's like asymetrical encryption: you can get a determined output from a seed; but you can't get a specific seed out of a list of picked assets?

I'll just stick with saving the json of avatar assets picked I guess. :)
